### ISSUE TITLE
Maintaining

### ISSUE THREAD

**Issue by lnginyard** [lnginyard/materialize-snippets-vscode#4]
Hello,

I stumbled upon your project materialize-snippets-vscode while looking for a framework in VS Code and I am sorry to hear of the challenges you are facing in the country of Venezuela are facing and hope that you and everyone facing the challenges find a solution soon. That being said I would like to maintain this repository and hopefully find other developers who would like to contribute and keep the project flowing and going. Thanks in advance for considering me whether you do or not.

**Comment by leninalbertolp** [comment]
Hello, thank you for your kind words.

In the next hour you should be receiving the transfer request.

**Comment by lnginyard** [comment]
Hey sorry I'm just getting back to you but I have deleted the fork and should now be ready fpr the transfer. Would like to discuss some things with you to better take on and progress the project. May I email you if I find the need?

**Comment by lnginyard** [comment]
Apologies but the repository transfer have expired on my end. I was busy over the weekend and hadn't gotten on GitHub. Can you reactivate the repository transfer so that I can accept it?
